apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak
data:
  KC_PROXY_HEADERS: xforwarded
  KC_HTTP_ENABLED: "true"
  KC_HOSTNAME: https://demo.kommonitor.de/keycloak/
  KC_DB: postgres
  KC_DB_URL_HOST: keycloak-db
  KC_DB_URL_PORT: "5432"
  KC_DB_URL_DATABASE: keycloak-data
  KC_DB_SCHEMA: public