apiVersion: apps/v1
kind: Deployment
metadata:
  name: kommonitor-data-management
  labels:
    app: kommonitor-data-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kommonitor-data-management
  template:
    metadata:
      labels:
        app: kommonitor-data-management
    spec:
      containers:
      - name: kommonitor-data-management
        image: kommonitor/data-management:4.1.5
        imagePullPolicy: Always
        resources:
          requests:
            memory: "300M"
            cpu: "10m"
          limits:
            memory: "1024M"
            cpu: "1000m"
        ports:
        - containerPort: 8087
        env:
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: kommonitor-db
              key: kommonitor.db.user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kommonitor-db
              key: kommonitor.db.password
        - name: KEYCLOAK_CREDENTIALS_SECRET
          valueFrom:
            secretKeyRef:
              name: kommonitor-data-management
              key: keycloak.secret
        envFrom:
        - configMapRef:
            name: kommonitor-data-management
        - configMapRef:
            name: kommonitor-keycloak