apiVersion: v1
kind: ConfigMap
metadata:
  name: kommonitor-processing-scheduler
data:
  #####################
  #      General      #
  #####################
  # URL to Data Management service; use docker name and port within same network if possible
  KOMMONITOR_DATA_MANAGEMENT_URL: http://kommonitor-data-management:8085/management
   # URL to Processing Engine service; use docker name and port within same network if possible
  KOMMONITOR_PROCESSING_ENGINE_URL: http://kommonitor-processing-engine:8086/processing
  # CRON pattern (refer to https://www.npmjs.com/package/node-cron) for periodic scheduler triggering
  # to initialize missing indicator time-series elements  
  CRON_PATTERN_FOR_SCHEDULING: "*/5 * * * *"
  # default false; global setting whether the computed indictor values from the hierarchically lowest
  # spatial unit shall be aggregated to hierarchically higher spatial units (true) or if each spatial
  # unit shall be computed own their own (false - required that base data is available on the respective spatial units)
  SETTING_AGGREGATE_SPATIAL_UNITS: "false"
  # boolean global setting to let scheduler retrigger already computed indicator time-series elements
  # for a certain period in time; good for use cases where historic base data is changed due to new facts,
  # and indicator data - computed from that base data - must be recomputed; applies globally to all
  # computed indicators currently  
  TRIGGER_COMPUTATION_OF_PAST_TIMESTAMPS_OVERWRITING_EXISTING_VALUES: "false"
  # number of days within the past to recompute indicator time series values - only relevant if
  # TRIGGER_COMPUTATION_OF_PAST_TIMESTAMPS_OVERWRITING_EXISTING_VALUES: true
  NUMBER_OF_DAYS_FOR_OVERWRITING_EXISTING_VALUES: "7"
  # optionally disable any console logs
  DISABLE_LOGS: "false"
  # if set to true, then the last possible timestamp from any baseIndicator is used; i.e. if there are
  # two base indicators A and B where lastTimestamp(A): 2019-12-31 and lastTimestamp(B): 2020-06-31,
  # then 2020-06-31 is used; if set to false, then 2019-12-31 will be used instead (as this is the latest
  # "common" date across all baseIndicators) 
  USE_LATEST_POSSIBLE_BASE_INDICATOR_DATE_INSTEAD_OF_COMMON_DATE: "true" 

  #####################
  #     Keycloak      #
  #####################
  # Keycloak client/resource name
  KEYCLOAK_RESOURCE: kommonitor-processing-scheduler 
  # name of kommonitor admin role within keycloak - default is 'kommonitor-creator'
  KOMMONITOR_ADMIN_ROLENAME: kommonitor-creator