apiVersion: apps/v1
kind: Deployment
metadata:
  name: kommonitor-processing-scheduler
  labels:
    app: kommonitor-processing-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kommonitor-processing-scheduler
  template:
    metadata:
      labels:
        app: kommonitor-processing-scheduler
    spec:
      containers:
      - name: kommonitor-processing-scheduler
        image: kommonitor/processing-scheduler:2.1.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "48M"
            cpu: "5m"
          limits:
            memory: "1024M"
            cpu: "1000m"
        ports:
        - containerPort: 8086
        env:
        - name: KEYCLOAK_ADMIN_RIGHTS_USER_NAME
          valueFrom:
            secretKeyRef:
              name: kommonitor-processing-scheduler
              key: admin.username
        - name: KEYCLOAK_ADMIN_RIGHTS_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kommonitor-processing-scheduler
              key: admin.password
        - name: KEYCLOAK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: kommonitor-processing-scheduler
              key: keycloak.secret
        envFrom:
        - configMapRef:
            name: kommonitor-processing-scheduler
        - configMapRef:
            name: kommonitor-keycloak